spring.thymeleaf.cache=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
server.compression.enabled=true
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-exception=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
